### ISSUE TITLE
Update webdriverio version

### ISSUE THREAD

**Issue by astoilkov** [senthanal/gulp-jasmine-webdriverio#2]
Any plans to upgrade webdriverio version. I am using this package but need to a newer version of webdriverio.

Great work with this repo.

**Comment by senthanal** [comment]
Do you mean webdriverio 3.2.0?

**Comment by astoilkov** [comment]
Yes. Maybe I schedule where you upgrade the version of webdriver.io when they release will be great.

**Comment by senthanal** [comment]
okay, no problem!

**Comment by astoilkov** [comment]
Thanks!

**Comment by senthanal** [comment]
Hi, I had a look. Seems upgrading issues. Something has been changed in the webdriverio version 3.0. I had a look also gulp-webdriverio project, haven't got updated. I have to dig in deeper. Will have look during weekend.

**Comment by astoilkov** [comment]
I can help you a little with that. I have been struggling with this today. Some of the changes I noticed:
- You should now work only with the latest returned instanced after executing client method. For example the previous code `client.keys('text'); client.keys('more text');` should be transformed to `client = client.keys('text'); client.keys('more text');` in order to work.
- Everything is now promises. Previously commands like `execute()` would take a callback parameter but they now work only with promises.

```
// before
client.execute(callback, function (err, result) {
  if (err) {
    throw err;
  }
  resolve();
});
// now
client.execute(callback).then(function (result) {
  resolve();
});
```

Hope this helps. :)

**Comment by senthanal** [comment]
Yes, I saw the comment from @christian-bromann, here, https://groups.google.com/forum/#!topic/webdriverio/b7cFK-4Qwo4. I use webdriverjs-angular library for angular projects. I think, these might also have to be upgraded. Lets see...
