### ISSUE TITLE
PhantomJS is a requirement, but is not described in package.json

### ISSUE THREAD

**Issue by spaceribs** [senthanal/gulp-jasmine-webdriverio#5]
https://github.com/senthanal/gulp-jasmine-webdriverio/blob/master/index.js#L16
Currently errors out when phantomjs is not installed.

**Comment by senthanal** [comment]
hi, phantomjs added as devDependencies. Please see here, https://github.com/senthanal/gulp-jasmine-webdriverio/blob/master/package.json#L75

Still do you get errors?

**Comment by spaceribs** [comment]
Because it's a devDependency, it's not being installed when made a requirement of a package

**Comment by senthanal** [comment]
I moved the phantomjs from devDependencies to dependencies block. Hope it helps.

**Comment by spaceribs** [comment]
Thanks! this works
